services:
  app:
    image: todo-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database?authSource=admin
    container_name: todo-backend-dev
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=the_username
      - MONGO_INITDB_ROOT_PASSWORD=the_password
      - MONGO_INITDB_DATABASE=the_database
    ports:
      - 3456:27017
    volumes:
      - ./mongo_data_fresh:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
